/// <reference types="next" />
/// <reference types="next/image-types/global" />

import "./.next/types/routes.d.ts";
import "./.next/types/root-params.d.ts";

// Auto-generated by Next.js.
// Manual changes to this file may be overwritten.
// See the Next.js TypeScript documentation for details.
